---
- name:  ping (and pong) for Linux
  hosts: 'vm_linux'
  gather_facts: false
  roles:
    - { role: ping_role }

- name:  ping (and pong) for Windows
  hosts: 'vm_windows'
  gather_facts: false
  roles:
    - { role: ping_role }
